### PR TITLE
De-aergaegaergearger'ing.

### PR DESCRIPTION
**Pull request by jesseleite**
Or was this intended?

### CODE REVIEW

**Comment by jackmcdade** [comment]
:joy:

**Comment by DanielCoulbourne** [comment]
Lolllll

**Comment by notasausage** [comment]
I was quite enjoying the aergaegaergeargering myself...

**Comment by jackmcdade** [comment]
Chancho, when you are a man, sometimes you aergaegaergearger in your room. Just for fun.

**Comment by jasonvarga** [comment]
Please make sure this ends up in the changelog.

**Comment by jhull** [comment]
I saw that! But loved it so much I didn’t want to say anything 🤣

--
Jim Hull
Narrative First
http://narrativefirst.com

**Pull request merged**
